recommendation:
  _target_: src.managers.RecommendationManager
  embedding: ${model.embedding}
  reranker: ${model.reranker}
  index: ${database}
  lab_id_column_name: ${lab_id_column_name}
  category_column_name: ${category_column_name}
  category_name_column_name: ${category_name_column_name}
  target_column_name: ${target_column_name}
  amount_column_name: ${amount_column_name}
  score_column_name: ${score_column_name}
  rerank_top_k: ${top_k.rerank}
  input_mode: ${input_mode}
  is_table: ${is_table}

report:
  _target_: src.managers.ReportManager
  generator: ${model.generator}